CREATE TABLE BOOKING (
  BOOKING_ID int auto_increment,
  USER_ID    int NOT NULL,
  ROOM_ID    int NOT NULL,
  FROM_DATE     date NOT NULL,
  UNTIL_DATE      date NOT NULL,
  PRICE      int NOT NULL,
  PRIMARY KEY (BOOKING_ID));
CREATE TABLE BOOKING_OPTION_DATA (
  OPTION_ID  int NOT NULL,
  BOOKING_ID int NOT NULL,
  PRIMARY KEY (OPTION_ID,
  BOOKING_ID));
CREATE TABLE CATEGORY (
  CATEGORY_ID int NOT NULL,
  DESCRIPTION varchar(255) NOT NULL,
  PRIMARY KEY (CATEGORY_ID));
CREATE TABLE BOOKING_OPTION (
  OPTION_ID   int auto_increment,
  DESCRIPTION varchar(255) NOT NULL,
  PRICE       int NOT NULL,
  PRIMARY KEY (OPTION_ID));
CREATE TABLE ROOM (
  ROOM_ID     int auto_increment,
  CATEGORY_ID int NOT NULL,
  NUMBER      int NOT NULL,
  PRICE       int NOT NULL,
  PRIMARY KEY (ROOM_ID));
CREATE TABLE CLIENT (
  USER_ID int auto_increment,
  USERNAME    varchar(255) NOT NULL,
  PRIMARY KEY (USER_ID));
ALTER TABLE BOOKING ADD CONSTRAINT FKBOOKING36416 FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ROOM_ID);
ALTER TABLE ROOM ADD CONSTRAINT FKROOM730787 FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID);
ALTER TABLE BOOKING_OPTION_DATA ADD CONSTRAINT FKBOOKING_OP483936 FOREIGN KEY (OPTION_ID) REFERENCES BOOKING_OPTION (OPTION_ID);
ALTER TABLE BOOKING_OPTION_DATA ADD CONSTRAINT FKBOOKING_OP899898 FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING (BOOKING_ID);
ALTER TABLE BOOKING ADD CONSTRAINT FKBOOKING46057 FOREIGN KEY (USER_ID) REFERENCES CLIENT (USER_ID);